# Project 3

Required libraries imported below

In [1]:
import matplotlib as plt
import numpy as np
import random

Data Generation

In [2]:
def is_dangerous(color_choices):
    if 3 in color_choices and 1 not in color_choices:
        return True
    return False
    
def generate_wiring_diagram():
    
    diagram = np.zeros((20, 20), dtype=int) # Initializing a 20x20 blank diagram
    color_choices = [1, 2, 3, 4] # 1: Red, 2: Blue, 3: Yellow, 4: Green
    row_choices = list(range(0,20))
    col_choices= list(range(0,20))
    dangerous = False

    start_with_row = random.choice([True, False])
    
    if start_with_row:
        for i in range(4):
            if i%2 == 0:
                row = random.choice(row_choices)
                color = random.choice(color_choices)
                diagram[row, :] = color
                row_choices.remove(row)
                color_choices.remove(color)
                if not dangerous:
                    dangerous = is_dangerous(color_choices)
            else:
                col = random.choice(col_choices)
                color = random.choice(color_choices)
                diagram[:, col] = color
                col_choices.remove(col)
                color_choices.remove(color)
                if i == 1 and not dangerous:
                    dangerous = is_dangerous(color_choices)
                
    else:
        for i in range(4):
            if i%2 == 0:
                col = random.choice(col_choices)
                color = random.choice(color_choices)
                diagram[col, :] = color
                col_choices.remove(col)
                color_choices.remove(color)
                if not dangerous:
                    dangerous = is_dangerous(color_choices)
            else:
                row = random.choice(row_choices)
                color = random.choice(color_choices)
                diagram[:, row] = color
                row_choices.remove(row)
                color_choices.remove(color)
                if i == 1 and not dangerous:
                    dangerous = is_dangerous(color_choices)
            
    return diagram, dangerous


In [3]:
diagram , dangerous = generate_wiring_diagram()
print(diagram)
print(dangerous)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 4 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 4 0]]
False
